// <auto-generated />
using System;
using Data_Context.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data_Context.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260402155227_Fix_CategoryAndProductSeedData")]
    partial class Fix_CategoryAndProductSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data_Context.Data.Category", b =>
                {
                    b.Property<int>("Category_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Category_Id"));

                    b.Property<string>("Category_Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Category_Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Category_Id = 1,
                            Category_Name = "Fruits"
                        });
                });

            modelBuilder.Entity("Data_Context.Data.Customer", b =>
                {
                    b.Property<int>("Customer_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Customer_Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumberPhone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Customer_Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Customer_Id = 1,
                            Address = "Tehran",
                            FirstName = "AmirMohammad",
                            LastName = "Rafiey",
                            NumberPhone = "09123456789",
                            Password = "1234"
                        });
                });

            modelBuilder.Entity("Data_Context.Data.Detail", b =>
                {
                    b.Property<int>("Detail_Id")
                        .HasColumnType("int");

                    b.Property<string>("Detail_Color")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Detail_Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("In_Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Detail_Id");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            Detail_Id = 1,
                            Detail_Color = "Red",
                            Detail_Description = "Made From Mazandaran",
                            In_Stock = 10,
                            RegistrationDate = new DateTime(2026, 3, 29, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Data_Context.Data.Product", b =>
                {
                    b.Property<int>("Product_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Product_Id"));

                    b.Property<int>("Category_ID")
                        .HasColumnType("int");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Product_Price")
                        .HasColumnType("int");

                    b.HasKey("Product_Id");

                    b.HasIndex("Category_ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Product_Id = 1,
                            Category_ID = 1,
                            Product_Name = "Apple",
                            Product_Price = 10000
                        });
                });

            modelBuilder.Entity("ModelAss.Models.Customer_Product", b =>
                {
                    b.Property<int>("Product_id")
                        .HasColumnType("int");

                    b.Property<int>("Customer_id")
                        .HasColumnType("int");

                    b.HasKey("Product_id", "Customer_id");

                    b.HasIndex("Customer_id");

                    b.ToTable("Customer_Product");
                });

            modelBuilder.Entity("Data_Context.Data.Detail", b =>
                {
                    b.HasOne("Data_Context.Data.Product", "product")
                        .WithOne("detail")
                        .HasForeignKey("Data_Context.Data.Detail", "Detail_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("Data_Context.Data.Product", b =>
                {
                    b.HasOne("Data_Context.Data.Category", "category")
                        .WithMany("Products")
                        .HasForeignKey("Category_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("ModelAss.Models.Customer_Product", b =>
                {
                    b.HasOne("Data_Context.Data.Customer", "customer")
                        .WithMany("Fluent_ProductCustomers")
                        .HasForeignKey("Customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Context.Data.Product", "product")
                        .WithMany("Fluent_ProductCustomers")
                        .HasForeignKey("Product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");

                    b.Navigation("product");
                });

            modelBuilder.Entity("Data_Context.Data.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Data_Context.Data.Customer", b =>
                {
                    b.Navigation("Fluent_ProductCustomers");
                });

            modelBuilder.Entity("Data_Context.Data.Product", b =>
                {
                    b.Navigation("Fluent_ProductCustomers");

                    b.Navigation("detail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
